[package]
name = "vfioveth"
version = "0.1.0"
authors = ["Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>"]
edition = "2018"

[dependencies]
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
